# Adding a Docker Compose file in order to test the services locally

#moved the passwords to env file to prevent checkov errors
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U complianceops"]
      interval: 5s
      timeout: 3s
      retries: 5

  transaction:
    build:
      context: ../complianceops-transactionservice
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"

  gateway:
    build:
      context: ../complianceops-gatewayservice
    environment:
      API_KEY: ${API_KEY}
      TRANSACTION_SERVICE_URL: http://transaction:8000
    depends_on:
      transaction:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data: