replicaCount: 3

image:
  tag: "CHANGEME-git-sha"

env:
  REDIS_HOST: "redis.sanctions-platform.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "warn"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

podAnnotations:
  compliance.complianceops.io/audited: "true"
