replicaCount: 1

image:
  tag: "dev-latest"

env:
  SCREENING_SERVICE_URL: "http://screening.sanctions-platform.svc.cluster.local:8080"
  DATABASE_URL: ""     
  SQS_QUEUE_URL: ""    
  LOG_LEVEL: "debug"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
