replicaCount: 1

image:
  tag: "dev-latest"  

env:
  TRANSACTION_SERVICE_URL: "http://transaction.sanctions-platform.svc.cluster.local:8001"
  LOG_LEVEL: "debug"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
